# Cloudflare Account Connection Defaults
# zone: "example.com"
# zone_id: "023e105f4ecef8ad9ca31a8372d0c353"
account_id: "372e67954025e0ba6aaa6d586b9e0b59"
email: "user@example.com"
token: secret_token