- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_private_dir }}/{{ item.name }}.pem"
    size: "{{ item.size | default('2048')}}"
    state: "{{ item.state | default('present') }}"
    type: "{{ item.type | default('RSA') }}"
    owner: "{{ item.owner | default(ansible_user) }}"

- name: Generate CA CSR
  community.crypto.openssl_csr:
    path: "{{ ssl_csr_dir }}/{{ item.name }}.csr"
    privatekey_path: "{{ ssl_private_dir }}/{{ item.csr.signer | default(item.name) }}.pem"
    common_name: "{{ item.common_name | default(None) }}"
    state: "{{ item.state | default('present') }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default(ansible_user) }}"
    country_name: "{{ item.country_name | default(None) }}"
    email_address: "{{ item.email_address | default(None) }}"
    group: "{{ item.group | default(ansible_user_primary_group) }}"
    organization_name: "{{ item.organization_name | default(None) }}"
    organizational_unit_name: "{{ item.organizational_unit_name | default(None) }}"
    state_or_province_name: "{{ item.state_or_province_name | default(None) }}"
    subject: "{{ item.subject | default({}) }}"
    subject_alt_name: "{{ item.subject_alt_name | default([]) }}"

- name: Generate CA self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ ssl_certs_dir }}/{{ item.name }}.crt"
    privatekey_path: "{{ ssl_private_dir }}/{{ item.cert.signer | default(item.name) }}.pem"
    csr_path: "{{ ssl_csr_dir }}/{{ item.name }}.csr"
    state: "{{ item.state | default('present') }}"
    provider: selfsigned
    mode: "{{ item.mode | default('644') }}"
    group: "{{ item.group | default(ansible_user_primary_group) }}"
    owner: "{{ item.owner | default(ansible_user) }}"
    selfsigned_not_after: "{{ item.expiry | default('+7300d') }}"
    selfsigned_digest: "{{ item.digest | default('sha256') }}"
    selfsigned_version: "{{ item.version | default('3')}}"

- name: Build CA self-signed certificate chain
  include_tasks: chain.yml
  vars: 
    cert: "{{ item }}"
  when: item.chain is defined and item.chain