- name: Build Cert Chain
  vars:
    current: "{{ cert }}"
    chain: []
  set_fact:
    chain: "{{ ([ssl_certs_dir + '/' + current.name + '.crt'] + chain) | unique }}"
    current: "{{ ( (root_cas + intermediate_cas + entity_cas) | selectattr('name', '==', current.cert.signer) )[0] }}"
    chain_file: "{{ ssl_certs_dir }}/{{ cert.name }}.pem"
  when: current is not none # and current.cert.signer != current.name [to exclude root]
  loop: "{{ range(0, cas | length ) }}"
  loop_control:
    loop_var: _

- name: Create Chain File And Add Contents
  shell: |
    cat {{ chain | reverse | join(' ') }} > {{ chain_file }}