- name: Prepare TLS Dependencies
  include_tasks: prep.yml
  register: prep

- name: Configure CAs & Issue Certificates
  include_tasks: ca.yml
  register: cas
  loop: "{{ root_cas + intermediate_cas + entity_cas }}" # Ordered list based on dependency
  when: inventory_hostname in groups['control_node']

- name: Copy CAs From Control Node to Ansible Workstation Node
  fetch:
    src: "{{ ssl_certs_dir }}/{{ item.name }}.crt"
    dest: "{{ tmp_cas_dir }}/{{ item.name }}.crt"
    flat: true
  register: load
  loop: "{{ root_cas }}"
  when: inventory_hostname in groups['control_node']

- name: Add CAs To Trusted CAs For All Nodes
  include_tasks: trust.yml
  register: trust
  loop: "{{ root_cas }}"

# Run last
- name: Create Report Registry
  include_role:
    name: common
    tasks_from: registry
  vars:
    role_registry: 
      - "{{ prep }}"
      - "{{ cas }}"
      - "{{ load }}"
      - "{{ trust }}"