- name: Copy Root CAs From CA Node to Workstation Node
  fetch:
    src: "{{ ssl_certs_dir }}/{{ item.name }}.{{ item.ext | default('crt') }}"
    dest: "{{ tmp_cas_dir }}/{{ item.name }}.{{ item.ext | default('crt') }}"
    flat: true
  register: load
  run_once: true
  when: inventory_hostname in groups['ca']
  loop: "{{ root_cas }}"

- name: Push file to another node
  copy:
    src: "{{ tmp_cas_dir }}/{{ item.name }}.{{ item.ext | default('crt') }}"
    dest: "{{ ssl_trust_dir }}/{{ item.name }}.{{ item.ext | default('crt') }}"
  loop: "{{ root_cas }}"

- name: Update CA Trust
  shell: |
    update-ca-certificates