- name: Copy CAs From Control Node to Workstation Node
  tags:
    - control
  fetch:
    src: "{{ ssl_certs_dir }}/{{ item.name }}.crt"
    dest: "/tmp/cas/{{ item.name }}.crt"
    flat: true

- name: Push file to another node
  tags: 
    - worker
    - control
  copy:
    src: "/tmp/cas/{{ item.name }}.crt"
    dest: "{{ ssl_trust_dir }}/{{ item.name }}.crt"

- name: Update CA Trust
  tags: 
    - worker
    - control
  shell: |
    update-ca-certificates