# # # # # # # # # 
# Site Configs ##
# # # # # # # ### 

- hosts: all
  become: true
  roles:
    - common

- hosts: web_servers
  become: true
  roles:
    - web
  handlers:
    - include_tasks: roles/common/handlers/main.yml