# # # # # # # # # 
# Site Configs ##
# # # # # # # ### 

- hosts: all
  become: true
  roles:
    - common
    - supervisord
    - telegraf
    - fluentbit

- hosts: 
    - ca
    - web_server
    - worker_node
    - control_node
  become: true
  roles:
    - ca

- hosts: web_server
  become: true
  roles:
    - web

- hosts: 
    - grafana
  become: true
  roles:
    - grafana

- hosts: 
    - etcd
  become: true
  roles:
    - etcd

- hosts: 
    - telegraf
  become: true
  roles:
    - telegraf

- hosts: 
    - fluentbit
  become: true
  roles:
    - fluentbit

- hosts: 
    - supervisord
  become: true
  roles:
    - supervisord

# Run last
- hosts: all
  name: Report
  tasks:
    - name: Create & Email Report
      include_role:
        name: common
        tasks_from: report
      vars:
        registry: "{{hostvars[inventory_hostname]['registry']}}"
      when: hostvars[inventory_hostname]['registry'] is defined