ssl_trust_dir: /usr/local/share/ca-certificates
ssl_private_dir: /etc/ssl/private/
ssl_certs_dir: /etc/ssl/certs/
ssl_csr_dir: /etc/ssl/csr/
tmp_cas_dir: /tmp/cas/

v3_root_ca_ext: &v3_root_ca_ext # Extensions for a typical CA (`man x509v3_config`).
  basic_constraints: ["CA:TRUE" ]
  key_usage: ["digitalSignature", "cRLSign", "keyCertSign"]
  create_subject_key_identifier: true
  key_usage_critical: true
  basic_constraints_critical: true
v3_intermediate_ca_ext: &v3_intermediate_ca_ext # Extensions for a typical intermediate CA (`man x509v3_config`).
  <<: *v3_root_ca_ext
  basic_constraints: ["CA:TRUE", "pathlen:0"]
  create_subject_key_identifier: true
  basic_constraints_critical: true
v3_usr_cert_ext: &v3_usr_cert_ext # Extensions for client certificates (`man x509v3_config`).
  basic_constraints: ["CA:FALSE"]
  extended_key_usage: ["clientAuth", "emailProtection"]
  key_usage: ["nonRepudiation", "digitalSignature", "keyEncipherment"]
  create_subject_key_identifier: true
  key_usage_critical: true
v3_server_cert_ext: &v3_server_cert_ext # Extensions for server certificates (`man x509v3_config`).
  basic_constraints: ["CA:FALSE"]
  key_usage: ["digitalSignature", "keyEncipherment"]
  extended_key_usage: ["serverAuth"] 
  create_subject_key_identifier: true
  key_usage_critical: true
v3_crl_ext_ext: &v3_crl_ext_ext # Extension for CRLs (`man x509v3_config`).
v3_ocsp_ext: &v3_ocsp_ext # Extension for OCSP signing certificates (`man ocsp`).
  basic_constraints: ["CA:FALSE"]
  key_usage: ["digitalSignature"]
  extended_key_usage: ["OCSPSigning"]
  create_subject_key_identifier: true
  key_usage_critical: true
  extended_key_usage_critical: true

root_cas:
  - name: prometejs.root 
    cert:
      signer: prometejs.root 
    csr:  
      common_name: prometejs.root
      <<: *v3_root_ca_ext

intermediate_cas:
  - name: prometejs.intermediate
    cert:
      signer: prometejs.root
    csr:
      common_name: prometejs.intermediate
      <<: *v3_intermediate_ca_ext

entity_cas:
  - name: etcd.edge
    chain: true
    cert:
      signer: prometejs.intermediate
    csr:
      <<: *v3_usr_cert_ext
      common_name: etcd.prometejs.io
      subject_alt_name: 
        - DNS:etcd.dev.prometejs.io
        - DNS:etcd.staging.prometejs.io
  - name: nats.edge
    chain: true
    cert:
      signer: prometejs.intermediate
    csr:
      <<: *v3_usr_cert_ext
      common_name: nats.prometejs.io
      subject_alt_name: 
        - DNS:nats.dev.prometejs.io
        - DNS:nats.staging.prometejs.io
  - name: web.edge
    chain: true
    cert:
      signer: prometejs.intermediate
    csr:
      <<: *v3_server_cert_ext
      common_name: prometejs.io
      subject_alt_name: 
        - DNS:*.prometejs.io
        - DNS:dev.prometejs.io
        - DNS:*.dev.prometejs.io
        - DNS:staging.prometejs.io
        - DNS:*.staging.prometejs.io