ssl_trust_dir: /usr/local/share/ca-certificates
ssl_private_dir: /etc/ssl/private/
ssl_certs_dir: /etc/ssl/certs/
ssl_csr_dir: /etc/ssl/csr/
tmp_cas_dir: /tmp/cas/

root_cas:
  - name: prometejs.root 
    cert:
      signer: prometejs.root 
    csr:  
      common_name: prometejs.root

intermediate_cas:
  - name: prometejs.intermediate
    chain: false
    cert:
      signer: prometejs.root
    csr:
      common_name: prometejs.intermediate

entity_cas:
  - name: etcd.edge
    chain: true
    cert:
      signer: prometejs.intermediate
    csr:
      common_name: etcd.prometejs.io
      subject_alt_name: 
        - DNS:etcd.dev.prometejs.io
        - DNS:etcd.staging.prometejs.io
  - name: nats.edge
    chain: true
    cert:
      signer: prometejs.intermediate
    csr:
      common_name: nats.prometejs.io
      subject_alt_name: 
        - DNS:nats.dev.prometejs.io
        - DNS:nats.staging.prometejs.io
  - name: web.edge
    chain: true
    cert:
      signer: prometejs.intermediate
    csr:
      common_name: prometejs.io
      subject_alt_name: 
        - DNS:*.prometejs.io
        - DNS:dev.prometejs.io
        - DNS:*.dev.prometejs.io
        - DNS:staging.prometejs.io
        - DNS:*.staging.prometejs.io