- name: Add InfluxDB repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu stable InfluxDB"
    state: present
    filename: influxdb

- name: Install InfluxDB Server & CLI
  package:
    name: "{{ item }}"
    state: present
  loop:
    - influxdb2
    - influx
    - python3-pip
    - psycopg2

- name: Start InfluxDB Server
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Enable InfluxDB as a service
  systemd:
    name: influxdb
    enabled: yes
    state: started

- name: Manage Users [Influxdb]
  community.general.influxdb_user:
    user_name: "{{ item.user_name }}"
    user_password: "{{ item.user_password }}"
    login_username: "{{ item.login_username | default('root') }}"
    login_password: "{{ item.login_password |  default(None) }}"
    hostname: "{{ item.hostname | default('localhost') }}"
    port: "{{ item.port | default('8086') }}"
    admin: "{{ item.admin | default(false) }}"
    grants: "{{ item.grants | default(None) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ influxdb_users }}"

- name: Manage Databases [Influxdb]
  community.general.influxdb_database:
    database_name: "{{ item.database_name }}"
    hostname: "{{ item.hostname | default('localhost') }}"
    username: "{{ item.login_username | default(None) }}"
    password: "{{ item.login_password |  default(None) }}"
    ssl: "{{ item.ssl | default(false) }}"
    validate_certs: "{{ item.validate_certs | default(false) }}"
    state: "{{ item.state | default('present') }}"
    port: "{{ item.port | default('8086') }}"
  loop: "{{ influxdb_databases }}"

# - name: Manage InfluxDB Config
#   template:
#     src: templates/influxdb.conf.j2
#     dest: /etc/influxdb/influxdb.conf
#     mode: '0444'
#   notify: restart_influxdb_server