- name: Add PostgreSQL repository
  apt_repository:
    repo: ppa:postgresql/ppa
    state: present

- name: Install PostgreSQL
  package:
    name: postgresql-server
    state: present

- name: Start PostgreSQL Service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Enable PostgreSQL as a service
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Manage Users
  postgresql_user:
    db: "{{ db | default('postgres') }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
  loop: "{{ postgresql_users }}"

- name: Manage Databases
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    maintenance_db: "{{ maintenance_db | default('postgres') }}" # initial database that ansible connects to
    login_host: "{{ item.host | default('127.0.0.1') }}"
    login_user: "{{ item.login_username | default(None) }}"
    login_password: "{{ item.login_password |  default(None) }}"
    port: "{{ item.port | default('5432') }}"
  loop: "{{ postgresql_databases }}"

- name: Manage User Provileges
  community.postgresql.postgresql_privs:
    database: "{{ item.maintenance_db | default('postgres') }}" # name of database to connect to
    login_host: "{{ item.host | default('127.0.0.1') }}"
    login_user: "{{ item.login_username }}"
    login_password: "{{ item.login_password }}"
    port: "{{ item.port | default('5432') }}"
    state: "{{ item.state | default('present') }}"
    schema: "{{ item.schema | default('public') }}" # schema that contains the database objects specified via objs.
    objs: "{{ item.object_names | default(None) }}" 
    roles: "{{ item.name }}" # comma separated list of role names to set permissions for.
    type: "{{ item.type_of_objects | default(None) }}" 
  loop: "{{ postgresql_users }}"

# get postgres version
# - name: Manage Postgresql Config
#   template:
#     src: templates/postgresql.conf.j2
#     dest: /etc/postgresql/<version>/main/postgresql.conf
#     mode: '0444'
#   notify: restart_postgresql_server