---
- name: Update NGINX configuration
  gather_facts: true
  hosts: web_servers
  become: true
  tasks:
    - name: Remove default NGINX configuration file
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy new default NGINX configuration file
      ansible.builtin.copy:
        src: ../../files/nginx/*.conf
        dest: /etc/nginx/sites-enabled/
        owner: root
        group: root
        mode: '0600'
      notify:
        - restart nginx

    - name: Create/Check nginx log path
      ansible.builtin.file:
        path: /var/logs/
        state: directory
        mode: '0755'

    - name: Create/Check ssl certificates directory
      ansible.builtin.file:
        path: /etc/ssl/
        state: directory
        mode: '0755'

    - name: Copy certificates
      ansible.builtin.copy:
        src: ../../files/certs/
        dest: /etc/ssl/
        owner: root
        group: root
        mode: '0400'

    - name: Create/Check ssl certificate keys directory
      ansible.builtin.file:
        path: /etc/ssl/keys/
        state: directory
        mode: '0755'

    - name: Copy certificate keys
      ansible.builtin.copy:
        src: ../../files/keys/
        dest: /etc/ssl/keys/
        owner: root
        group: root
        mode: '0400'
        
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        daemon_reload: yes
