
- name: Clone default site main branch
  gather_facts: true
  hosts: web_servers
  become: true
  vars:
    deploy_key: ~/.ssh/ansible
  tasks:
    - name: Create/Check clone directory exist
      ansible.builtin.file:
        path: /var/www/prometejs.ddns.net/
        state: directory
        mode: '0755'

    - name: Clone the Git repository to a temporary location
      ansible.builtin.git:
        repo: git@github.com:Prometejs/ansibles.git
        dest: '/tmp/site'
        single_branch: yes
        version: 'main' 
        key_file: "{{ deploy_key }}"
      register: git_clone
    
    - name: Copy specific directory from the cloned repo to the target location
      command: cp -r /tmp/site/src/* /var/www/prometejs.ddns.net/
      when: git_clone.changed

    - name: Clean up temporary repository clone
      file:
        path: '/tmp/site'
        state: absent
      when: git_clone.changed