#########################################################################
# Executed for each element in `bitcoin_gpg_builders_pub_key`
# Verifies the integrity and authenticity of downloaded SHA256SUMS files
#########################################################################
---
- name: "Bitcoind | Ensure '/tmp/gpg-{{ gpg_signer }}' directory exists"
  ansible.builtin.file:
    path: /tmp/gpg-{{ gpg_signer }}
    state: directory

- name: "Bitcoind | Download Signer '{{ gpg_signer }}' GPG Public Key For v{{ bitcoin_version }}"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/bitcoin-core/guix.sigs/main/builder-keys/{{ gpg_signer }}
    dest: '{{ gpg_home_dir }}/bitcoin-v{{ bitcoin_version }}-{{ gpg_signer }}.gpg'
    http_agent: '{{http_agent}}'

- name: "Bitcoind | Download Signer '{{ gpg_signer }}' Detached Signature For v{{ bitcoin_version }}"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/bitcoin-core/guix.sigs/main/{{ bitcoin_version }}/{{ gpg_signer }}/all.SHA256SUMS.asc
    dest: /tmp/gpg-{{ gpg_signer }}/all.SHA256SUMS.asc
    http_agent: '{{http_agent}}' 

- name: "Bitcoind | Verify authenticity of '/tmp/SHA256SUMS' (Bitcoin v{{ bitcoin_version }})"
  shell: gpg --keyring {{ gpg_home_dir }}/bitcoin-v{{ bitcoin_version }}-{{ gpg_signer }}.gpg --no-default-keyring --verify /tmp/gpg-{{ gpg_signer }}/all.SHA256SUMS.asc /tmp/SHA256SUMS
  changed_when: false