- name: Install `bitcoind` 
  include_tasks: install.yml
  register: install

- name: Configure `bitcoind`
  include_tasks: setup.yml
  register: setup

- name: Run `bitcoind` Service
  include_tasks: run.yml
  register: run

# Run last
- name: Create Report Registry
  include_role:
    name: common
    tasks_from: registry
  vars:
    role_registry: 
      - "{{ install }}"
      - "{{ setup }}"
      - "{{ run }}"