---
###########################
# Group & User management
###########################
- name: "Bitcoind | Ensure '{{ bitcoin_group }}' group exists"
  ansible.builtin.group:
    name: "{{ bitcoin_group }}"
    state: present

- name: "Bitcoind | Ensure '{{ bitcoin_user }}' user with '{{ bitcoin_group }}' group exists"
  ansible.builtin.user:
    name: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    state: present
    password: "*" # locks/disables password on Linux systems for user

###############################
# GPG & SHA256SUMS management
###############################
- name: "Bitcoind | Download SHA256SUMS for Bitcoin v{{ bitcoin_version }} into '/tmp/bitcoin-core-v{{ bitcoin_version }}/SHA256SUMS'"
  ansible.builtin.get_url:
    url: https://bitcoincore.org/bin/bitcoin-core-{{ bitcoin_version }}/SHA256SUMS
    dest: /tmp/bitcoin-core-v{{ bitcoin_version }}/SHA256SUMS
    http_agent: '{{http_agent}}'

- name: "Bitcoind | Install GPG public key defined in `bitcoin_gpg_signer_pub_key` and verify SHA256SUMS"
  include_tasks: gpg.yml
  vars:
    gpg_signer: "{{ item }}"
  loop: "{{ bitcoin_gpg_signer_pub_key }}"
  when: bitcoin_gpg_signer_pub_key is defined and bitcoin_gpg_signer_pub_key | length > 0

##########################
# Bitcoind configuration
##########################
- name: "Bitcoind | Ensure Bitcoin data directory '{{ bitcoin_data_dir }}' exists"
  ansible.builtin.file:
    path: "{{ bitcoin_data_dir }}"
    state: directory
    owner: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    mode: 0750

- name: "Bitcoind | Ensure Bitcoin configuration directory '/etc/bitcoin/{{ bitcoin_network }}' exists"
  ansible.builtin.file:
    path: /etc/bitcoin/{{ bitcoin_network }}
    state: directory
    owner: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    mode: 0750

- name: "Bitcoind | Load bitcoin.conf configuration"
  ansible.builtin.template:
    src: bitcoin.conf.j2
    dest: /etc/bitcoin/{{ bitcoin_network }}/bitcoin.conf
    owner: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
  notify:
    - restart_bitcoind

- name: "Bitcoind | Load service/unit configuration"
  ansible.builtin.template:
    src: bitcoind.service.j2
    dest: /etc/systemd/system/bitcoind-{{ bitcoin_network }}.service
  notify:
    - restart_bitcoind