- name: Install Web Server
  include_tasks: nginx.yml
  register: nginx  

- name: Configure Sites SSL
  include_tasks: ssl.yml
  register: ssl
  loop:
    - src: files/prometejs/prometejs.key
      path: "{{ssl_private_path}}"
      owner: www-data
      mode: '0400'
    - src: files/prometejs/prometejs.pem
      path: "{{ssl_certs_path}}"
      owner: www-data
      mode: '0444'

- name: Set Up Prometejs
  include_tasks: prometejs.yml
  register: prometejs

- name: Deploy Site Nginx Configs
  include_tasks: sites.yml
  register: sites
  loop:
    - name: prometejs
      src: files/prometejs/prometejs.conf
      enabled: False

# Run last
- name: Create Report Registry
  include_role:
    name: common
    tasks_from: registry
  vars:
    role_registry: 
      - "{{ nginx }}"
      - "{{ ssl }}"
      - "{{ prometejs }}"
      - "{{ sites }}" 