- name: Configure Nginx Web Server
  include_tasks: nginx.yml
  register: nginx 

- name: Configure SSL Certs
  include_tasks: ssl.yml
  register: ssl

- name: Install Apps
  include_tasks: "{{ item }}"
  register: install
  loop:
    - apps/prometejs.yml

# # revisit
# - name: Deploy Nginx Sites
#   include_tasks: sites.yml
#   register: sites
#   loop: "{{ nginx_sites }}"

# # Run last
# - name: Create Report Registry
#   include_role:
#     name: common
#     tasks_from: registry
#   vars:
#     role_registry: 
#       - "{{ nginx }}"
#       - "{{ ssl }}"
#       - "{{ install }}"
#       # - "{{ sites }}" 