- name: Install NGINX
  package:
    name: nginx
    state: latest
    update_cache: yes

- name: Start and enable NGINX
  service:
    name: nginx
    state: started
    enabled: yes

- name: Remove Default Site Config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent