- name: Install Nginx
  package:
    name: nginx
    state: latest
    update_cache: yes
  notify: start_enable_nginx

- name: Configure Sites Directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nginx_sites_enabled_path }}/http"
    - "{{ nginx_sites_enabled_path }}/stream"
    - "{{ nginx_sites_available_path }}/http"
    - "{{ nginx_sites_available_path }}/stream"

- name: Add Nginx Configuration
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart_nginx

- name: Add Nginx User Required Groups
  user:
    name: "{{ nginx_user }}"
    groups: "{{ item }}"
    append: yes
  loop:
    - "{{ ssl_cert_group | default('ssl-cert') }}"
    - "{{ super_user | default('ssl-cert') }}"