- name: Add Sites [{{ item.name | upper }}]
  vars:
    site: "{{ item.config }}"
  ansible.builtin.template:
    src: "templates/sites.conf.j2"
    dest: &config_path "{{ nginx_sites_available_path }}/{{ item.protocol }}/{{ item.name }}.conf"
    owner: "{{ item.owner | default(nginx_user) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default('0440') }}"

- name: Enable Sites [{{ item.name | upper }}]
  ansible.builtin.file:
    src: *config_path
    dest: "{{ nginx_sites_enabled_path }}/{{ item.protocol }}/{{ item.name }}.conf"
    owner: "{{ item.owner | default(nginx_user) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default('0440') }}"
    state: "{{ 'link' if item.enable else 'absent' }}"
  notify:
    - restart_nginx