- name: Install Ubuntu Firewall
  apt:
    name: ufw
    state: "latest"
    update_cache: yes

- name: Start Ubuntu Firewall
  service:
    name: ufw
    state: started
    enabled: yes

- name: Allow SSH Traffic for Ubuntu Firewall
  ufw:
    rule: allow
    name: OpenSSH
  notify: Reload Ubuntu Firewall

- name: Allow HTTP Traffic for Ubuntu Firewall
  ufw:
    rule: allow
    port: '80'
  notify: Reload Ubuntu Firewall

- name: Allow HTTPS Traffic for Ubuntu Firewall
  ufw:
    rule: allow
    port: '443'
  notify: Reload Ubuntu Firewall



  # when: ansible_os_family == "Debian"

    # - name: Start and enable firewalld on CentOS
    #   service:
    #     name: firewalld
    #     state: started
    #     enabled: yes
    #   when: ansible_os_family == "RedHat"


  # when: ansible_os_family == "Debian"

# - name: Allow SSH through firewalld on CentOS
#   firewalld:
#     service: ssh
#     permanent: yes
#     state: enabled
#     immediate: yes
  # when: ansible_os_family == "RedHat"


#   when: ansible_os_family == "Debian"

# - name: Allow HTTP through firewalld on CentOS
#   firewalld:
#     port: 80/tcp
#     permanent: yes
#     state: enabled
#     immediate: yes
#   when: ansible_os_family == "RedHat"


  # when: ansible_os_family == "Debian"

# - name: Allow HTTPS through firewalld on CentOS
#   firewalld:
#     port: 443/tcp
#     permanent: yes
#     state: enabled
#     immediate: yes
#   when: ansible_os_family == "RedHat"

- name: Enable UFW on Ubuntu
  ufw:
    state: enabled
    default: deny
  when: ansible_os_family == "Debian"