- name: Install Ubuntu Firewall
  apt:
    name: ufw
    state: "latest"
    update_cache: yes

- name: Start Ubuntu Firewall
  service:
    name: ufw
    state: started
    enabled: yes

- name: Allow SSH Traffic for Ubuntu Firewall
  ufw:
    rule: allow
    name: OpenSSH
  notify: reload_ubuntu_firewall

- name: Allow HTTP Traffic for Ubuntu Firewall
  ufw:
    rule: allow
    port: '80'
  notify: reload_ubuntu_firewall

- name: Allow HTTPS Traffic for Ubuntu Firewall
  ufw:
    rule: allow
    port: '443'
  notify: reload_ubuntu_firewall