- name: Update Cache
  include_tasks: cache.yml
  register: cache

- name: Configure Ansible User
  include_tasks: users.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  register: user

- name: Configure Firewall
  include_tasks: firewall.yml
  register: firewall

- name: Configure Git
  include_tasks: git.yml
  register: git

- name: Configure DNS Name Servers
  include_tasks: dns.yml
  register: dns

# Run last
- name: Create Report Registry
  include_tasks: registry.yml
  vars:
    role_registry: 
      - "{{ dns }}"
      - "{{ git }}"
      - "{{ user }}" 
      - "{{ firewall }}"
      - "{{ cache }}"