- name: Create Report
  set_fact:
    report: |
        {{  report | default("Execution Summary
        ") + '++' + item | string }}
  loop: "{{ registry }}"

- name: Trigger Handler For Report
  command: /bin/true
  when: report != (ansible_local | default({})).get('report', None)
  notify: send_email