- name: Create Report
  set_fact:
    report: |
        [{{ inventory_hostname }}]----{{  report | default("") + item | string + '\n' }}
  loop:   
    - "{{ cache }}"
    - "{{ user }}" 
    - "{{ firewall }}"

- name: Trigger Handler For Report
  command: /bin/true
  when: report != (ansible_local | default({})).get('report', None)
  notify: send_email