ssl_private_path: /etc/ssl/sites/private/
ssl_certs_path: /etc/ssl/sites/certs/
sites_available_path: /etc/nginx/sites-available/
sites_enabled_path: /etc/nginx/sites-enabled/
worker_connections: '1024'
nginx_user: www-data

web_certs:
  - name: prometejs.wildcard.edge
    chain: true
    cert:
      signer: prometejs.intermediate
    csr:
      common_name: '*.prometejs.io'
      country_name: GH
      organization_name: Prometejs
      organizational_unit_name: Web
      state_or_province_name: Greater Accra