# All hosts
[web_servers]
prometejs.ddns.net

[master_site]
prometejs.ddns.net

[worker_sites]
prometejs.ddns.net

# Dev hosts
[dev:web_servers]
prometejs.ddns.net

[dev:master_site]
prometejs.ddns.net

[dev:worker_sites]
prometejs.ddns.net

# Staging hosts
[staging:web_servers]
[staging:master_site]
[staging:worker_sites]

# Prod hosts
[prod:web_servers]
[prod:master_site]
[prod:worker_sites]