# All hosts
[web_servers]
prometejs.ddns.net

[master_site]
prometejs.ddns.net

[worker_sites]
prometejs.ddns.net

# Dev hosts group
[dev:children]
web_servers
master_site
worker_sites

# Staging hosts group
[staging:children]

# Prod hosts group
[prod:children]