# Default server
server {
    listen              443 ssl
    listen              [::]:443 ssl
    server_name         prometejs.ddns.net
    keepalive_timeout   60s

    access_log          logs/prometejs.ddns.access.log  main;
    error_log           logs/prometejs.ddns.error.log;

    ssl_certificate     /etc/ssl/
    ssl_certificate_key /etc/ssl/

    location / {
        root    /var/www/prometejs.ddns.net/html;
        index   index.$geo.html index.htm index.html;
    }

    location ~* \.(js|jpg|png|css)$ {
        root /usr/share/nginx/html/;
    }
}

# Redirect http to https
server {
    listen      80
    listen      [::]:80
    server_name prometejs.ddns.net
    return 301  https://prometejs.ddns.net$request_uri;
}

