# Default server
server {
    listen              443 ssl
    listen              [::]:443 ssl
    server_name         prometejs.ddns.net
    keepalive_timeout   60s

    access_log          /var/logs/prometejs.ddns.access.log  main;
    error_log           /var/logs/prometejs.ddns.error.log;

    ssl_certificate     /etc/ssl/prometejs_ddns_net.pem
    ssl_certificate_key /etc/ssl/keys/prometejs.key

    location / {
        root    /var/www/prometejs.ddns.net/;
        index   index.$geo.html index.htm index.html;
        try_files $uri $uri/ =404;
    }

    location ~* \.(js|jpg|png|css)$ {
        root /var/www/prometejs.ddns.net/;
        expires 1y; # Cache static files for 1 year
        access_log off; # Turn off logging for performance
        add_header Cache-Control "public";
    }

}

# Redirect http to https
server {
    listen      80
    listen      [::]:80
    server_name prometejs.ddns.net
    return 301  https://prometejs.ddns.net$request_uri;
}

