admin_mail: elvissegbawu@gmail.com
users:
  - name: hermes
    pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKOUuJHSylToQckXxKAU2atbtWDUcATKdoh6GckONzcM ansible ssh [hermes]" # lookup('file', 'hermes.pub')"
    groups: 
      - root
    sudoers:
      src: files/sudoers/hermes
      dest: /etc/sudoers.d/hermes
      owner: root
      group: root
      mode: "0440"
  - name: apollo
    groups: 
      - root
  - name: athena
  - name: zues

  

