admin_mail: elvissegbawu@gmail.com
users:
  - name: hermes
    groups: 
      - root
    sudoers:
      src: files/sudoers/hermes
      dest: /etc/sudoers.d/hermes
      owner: root
      group: root
      mode: "0440"
  - name: apollo
    groups: 
      - root