---
- name: Configure Ansible User
  hosts: all
  become: yes
  tasks:
    - name: create hermes user
      user:
        name: hermes
        groups: root

    - name: add ssh key for hermes
      authorized_key:
        user: hermes
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKOUuJHSylToQckXxKAU2atbtWDUcATKdoh6GckONzcM ansible ssh [hermes]"
         
    - name: add sudoers file for hermes
      copy:
        src: files/sudoers/hermes
        dest: /etc/sudoers.d/hermes
        owner: root
        group: root
        mode: 0440