name: Ansible Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Setup All Dependencies
        uses: ./.github/actions/dependencies
        with:
          test: "true"

      - name: Run Ansible syntax check
        run: |
          ansible-playbook --syntax-check playbook.yml
          echo "Checking Syntax `setup.yml` ..." && ansible-playbook --syntax-check setup.yml
          echo "Checking Syntax `site.yml` ..." && ansible-playbook --syntax-check site.yml

      - name: Run Ansible check mode
        run: |
          echo "Dry Run `setup.yml` ..." && ansible-playbook setup.yml --check
          echo "Dry Run `site.yml` ..." && ansible-playbook site.yml --check
          
      - name: Run Role Test With Molecule
        run: |
          for role in ./roles/*; do
            if [ -d "$role" ]; then
              cd ./roles/$role && molecule test
            fi
          done