name: Ansible Tests

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel previous runs of the same workflow for the same branch

jobs:
  ansible-test:
    runs-on: ubuntu-latest # tbd
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Ansible Syntax Check
        run: |
          echo "Checking Syntax -> setup.yml ..." && ansible-playbook --syntax-check setup.yml
          echo "Checking Syntax -> site.yml ..." && ansible-playbook --syntax-check site.yml
      
      - name: Ansible Check Mode
        run: |
          echo "Dry Run -> setup.yml ..." && ansible-playbook setup.yml --check
          echo "Dry Run -> site.yml ..." && ansible-playbook site.yml --check
          
      - name: Test Role [Molecule]
        run: |
          for role in ./roles/*; do
            if [ -d "$role" ]; then
              cd ./roles/$role && molecule test
            fi
          done