name: Bootstrap Sites

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        default: 'development'
        options:
          - development
          - production
          - staging  

jobs:
  bootstrap-sites:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Setup All Dependencies
        uses: ./.github/actions/dependencies
        env:
          VAULT_KEY: ${{ secrets.VAULT_KEY }}          

      - name: Execute Ansible
        run: |
          ansible-playbook setup.yml -vvv -i 'inventories/${{ inputs.environment }}'