name: Bootstrap Sites

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        default: 'development'
        options:
          - development
          - production
          - staging  

jobs:
  bootstrap-sites:
    runs-on: ubuntu-latest # tbd
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Install Dependencies
        uses: ./.github/actions/dependencies
        env:
          VAULT_KEY: ${{ secrets.VAULT_KEY }}          

      - name: Execute Ansible
        run: |
          ansible-playbook setup.yml -vvv -i 'inventories/${{ inputs.environment }}'