name: Configure Sites

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        default: 'development'
        options:
          - development
          - production
          - staging

jobs:
  run-tests:
    uses: ./.github/workflows/ci-test.yml

  configure:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Execute Ansible
        run: |
          ansible-playbook site.yml -vvv -i 'inventories/${{ inputs.environment }}'