name: Configure Sites

on:
  workflow_run:
    workflows:
      - Ansible Tests
    types:
      - completed
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        default: 'development'
        options:
          - development
          - production
          - staging

jobs:
  configure:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Setup All Dependencies
        uses: ./.github/actions/dependencies
        
      - name: Execute Ansible
        run: |
          ansible-playbook site.yml -vvv -i 'inventories/${{ inputs.environment }}'
        if: github.ref_name == 'main'