name: deploy configs to staging

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.1x

      - name: Install Ansible & Add Community Collections
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install community.general

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts
      
      - name: Run Host Setups
        run: |
          set -e
          for playbook in ./playbooks/setups/*.yaml; do
            if [ -f "$playbook" ]; then
              echo "Running playbook $playbook with verbosity level 3"
              ansible-playbook -i staging $playbook -vvv
            else
              echo "Skipping $playbook, not a file."
            fi
          done

      - name: Run Host Configurations
        run: |
          set -e
          for playbook in ./playbooks/configs/*.yaml; do
            if [ -f "$playbook" ]; then
              echo "Running playbook $playbook with verbosity level 3"
              ansible-playbook -i staging $playbook -vvv
            else
              echo "Skipping $playbook, not a file."
            fi
          done
